server:
  port: 8086
spring:
  application:
    name: research-service  #给当前微服务起个名字
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.100.130:8848   #nacos地址
    sentinel:
      enabled: true # 开启feign对sentinel的支持（让Feign也成为ClientSentinel的簇点资源）   -- 2.线程隔离
      transport:
        dashboard: 192.168.100.130:8090 # Sentinel Dashboard 的地址（IP:端口）
      http-method-specify: true  # 开启请求方式前缀(restful)  -- 1.请求限流
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${hm.db.host}:3306/hm-item?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${hm.db.pw}
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.hmall.item: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
#swagger文档
knife4j:
  enable: true
  openapi:
    title: 黑马商城elasticsearch搜索接口文档
    description: "黑马商城elasticsearch搜索接口文档"
    email: zhanghuyi@itcast.cn
    concat: 虎哥
    url: https://www.itcast.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.hmall.research.controller